apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: servicos
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    # - list:
    #     elements:
    #       - cluster: engineering-dev
    #         url: https://kubernetes.default.svc
    #       - cluster: engineering-prod
    #         url: https://kubernetes.default.svc
    #       - cluster: finance-preprod
    #         url: https://kubernetes.default.svc
    - git:
        repoURL: https://github.com/marlondaraujo/episode1
        revision: HEAD
        directories:
          - path: 'servicos/*'
          # - path: '**/_exclude/*'
          #   exclude: true
          # - path: 'root'
          #   exclude: true
  template:
    metadata:
      name: '{{ `{{path[0]}}` }}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/marlondaraujo/episode1
        targetRevision: HEAD
        path: servicos/{{ `{{path[0]}}` }}
      destination:
        server: '{{.server}}'
        namespace: '{{ `{{path[1]}}` }}'
