apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: essenciais-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - git:
        repoURL: https://github.com/marlondaraujo/episode1
        revision: HEAD
        directories:
          - path: '20-workloads/essenciais/*'
  template:
    metadata:
      name: 'essenciais-{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/marlondaraujo/episode1
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}-apps'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
