apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicos 
spec:
  destination:
    name: ''
    namespace: apps
    server: 'https://kubernetes.default.svc'
  source:
    path: 'servicos'  
    repoURL: 'https://github.com/marlondaraujo/episode1'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
